call pathogen#infect()

function! SuperCleverTab()
    if strpart(getline('.'), 0, col('.') - 1) =~ '^\s*$'
        return "\<Tab>"
    else
        if &omnifunc != ''
            return "\<C-X>\<C-O>"
        elseif &dictionary != ''
            return "\<C-K>"
        else
            return "\<C-N>"
        endif
    endif
endfunction

inoremap <Tab> <C-R>=SuperCleverTab()<cr>

map <C-F7> :! easytags.sh *<CR>

set tabstop=4
set sw=4
set nowrap
set mouse=a
set mousehide
set bg=dark
set expandtab
set cindent
set rnu
set tags+=/home/george/.vim/ctags'
set wildmenu
set list listchars=tab:»─,trail:·,precedes:←,extends:→

autocmd InsertEnter * : set number
autocmd InsertLeave * : set relativenumber
autocmd FocusLost   * : set number
autocmd FocusGained * : set relativenumber

filetype plugin on
syntax on

if has("gui_running")
    colorscheme torte
else
    colorscheme default
endif

