" My vimrc.
"
" Maintainer:		George Stamoulis <g.a.stamoulis@gmail.com>
" Last Change:		May 08 2013

" The plugins plugin.
execute pathogen#infect()

set nocompatible				" get rid of Vi compatibility mode.
filetype plugin indent on		" filetype detection[ON] plugin[ON] indent[ON].
syntax enable					" enable syntax highlighting (previously syntax on).
set directory=.,~/.vim/swap		" swap file directory.
set autoindent					" auto-indent.
set tabstop=4					" tab spacing.
set softtabstop=4				" unify.
set shiftwidth=4				" indent/outdent by 4 columns.
set shiftround					" always indent/outdent to the nearest tabstop.
set expandtab					" use spaces instead of tabs.
set smarttab					" use tabs at the start of a line, spaces elsewhere.
set nohlsearch					" don't continue to highlight searched phrases.
set incsearch					" but do hihglight as you type your search.
set ruler						" always show info along bottom.
set background=dark				" colorscheme info.
set relativenumber				" count distance from cursor.
set wildmenu					" enable wildmenu.
set nowrap						" don't wrap text.
set colorcolumn=120				" highlight the 120th column.
set list listchars=tab:»─,trail:·,precedes:←,extends:→

autocmd BufEnter    *   silent! lcd %:p:h

autocmd InsertEnter * : set number
autocmd InsertLeave * : set relativenumber
autocmd FocusLost   * : set number
autocmd FocusGained * : set relativenumber

" The Vim way =)
map <up>		<nop>
map <down>		<nop>
map <left>		<nop>
map <right>		<nop>

" Snipmate variables.
source $HOME/.vim/variables/snipvars.vim

if &term=~'xterm'
    hi Normal ctermbg=black ctermfg=grey cterm=none
elseif &term=~'linux'
    colorscheme default
endif
